Script started on 2019-03-04 20:22:34+0800
]0;pd2@VirtualBox: ~/Desktop/lab1[01;32mpd2@VirtualBox[00m:[01;34m~/Desktop/lab1[00m$ whoami; pwd
pd2
/home/pd2/Desktop/lab1
]0;pd2@VirtualBox: ~/Desktop/lab1[01;32mpd2@VirtualBox[00m:[01;34m~/Desktop/lab1[00m$ git config -l
[?1h=core.editor=vim[m
push.default=simple[m
user.name=Youqing[m
user.email=youqing1211@gmail.com[m
color.ui=auto[m
[K[?1l>]0;pd2@VirtualBox: ~/Desktop/lab1[01;32mpd2@VirtualBox[00m:[01;34m~/Desktop/lab1[00m$ git clone https ://pd2a.imslab.org/gitlab/Qing/lab1.git
Cloning into 'lab1'...
Username for 'https://pd2a.imslab.org': Qing
Password for 'https://Qing@pd2a.imslab.org': 
remote: Enumerating objects: 3, done.[K
remote: Counting objects:  33% (1/3)   [Kremote: Counting objects:  66% (2/3)   [Kremote: Counting objects: 100% (3/3)   [Kremote: Counting objects: 100% (3/3), done.[K
remote: Total 3 (delta 0), reused 0 (delta 0)[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;pd2@VirtualBox: ~/Desktop/lab1[01;32mpd2@VirtualBox[00m:[01;34m~/Desktop/lab1[00m$ ls
[0m[01;34mlab1[0m  lab1.script
]0;pd2@VirtualBox: ~/Desktop/lab1[01;32mpd2@VirtualBox[00m:[01;34m~/Desktop/lab1[00m$ exit

Script done on 2019-03-04 20:26:22+0800
